services:
  auth-api:
    image: public.ecr.aws/q2n5r5e8/ozrnds/project-shkedia-months-worker:${MONTHS_SERVICE_VERSION}
    container_name: shkedia_months_engine
    env_file: .local/months_engine_service.env
    environment:
      - DEBUG
    volumes:
      - ${HOST_MOUNT}:/temp
    restart: always